name: CI
on: pull_request
jobs:
  build_test_and_deploy:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nuxt/actions-yarn@97f98f200b7fd42a001f88e7bdfc14d64d695ab2
      - run: yarn install
      - run: yarn run build:icons
      - run: yarn run build:package
      - run: yarn test:unit
