name: Master Pipeline
on:
  push:
    branches:
      - master
jobs:
  build_test_and_deploy:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nuxt/actions-yarn@97f98f200b7fd42a001f88e7bdfc14d64d695ab2
      - run: yarn install
      - run: yarn build:icons
      - run: yarn build:package
      - run: yarn test:unit
      - uses: actions/npm@master
      - run: npm version $(npm show . version)-$(git rev-parse --short HEAD) --no-git-tag-version --unsafe-perm
      - run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
